package org.monostudio.jpa.entities;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.monostudio.jpa.DBEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.Size;

@Entity
@Table(
    name = "product_categories",
    uniqueConstraints = {
        @UniqueConstraint(columnNames = {"parent_product_category_id", "product_category_name"})
    })
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@EqualsAndHashCode
public class ProductCategory
    implements DBEntity {
    private static final long serialVersionUID = 11L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "product_category_id", nullable = false)
    private Long id;
    @Size(min = 1, max = 50)
    @Column(name = "product_category_code", nullable = false, unique = true)
    private String code;
    @Size(min = 1, max = 100)
    @Column(name = "product_category_name", nullable = false)
    private String name;
    @JoinColumn(name = "parent_product_category_id", referencedColumnName = "product_category_id")
    @ManyToOne(fetch = FetchType.LAZY)
    private ProductCategory parent;

    @JoinColumn(name = "image_id", referencedColumnName = "image_id")
    @ManyToOne(fetch = FetchType.LAZY)
    private Image image;

    @Column(name = "display_order", nullable = false)
    @Builder.Default
    private Integer displayOrder = 0;

    /**
     * Please note: this copy-constructor does NOT include a ProductCategory's relationship to its parent.
     *
     * @param source The original ProductCategory
     */
    public ProductCategory(ProductCategory source) {
        this.id = source.id;
        this.code = source.code;
        this.name = source.name;
        this.image = source.image;
        this.displayOrder = source.displayOrder;
        this.parent = null;
    }

    /**
     * This override prevents looping through the entire parent-tree.
     *
     * @return An equivalent result to lombok autogenerated toString() method,
     * except that this will only reveal info about its immediate parent.
     */
    @Override
    public String toString() {
        return "ProductCategory(" +
            "id=" + id +
            ", code='" + code + '\'' +
            ", name='" + name + '\'' +
            ((parent!=null) ?
                (", parent=ProductCategory(" +
                    "id=" + parent.id +
                    ", code=" + parent.code +
                    ", name=" + parent.name +
                    ')'
                ):
                ", parent=null") +
            ')';
    }
}
