monostudio.mailing.mailgun.api-key=
# The domain you've associated your Mailgun account to, and wish to send emails from
monostudio.mailing.mailgun.domain=
# Template name for mails sent to customers right after payment
monostudio.mailing.mailgun.customer-order-payment-template=
# Template name for mails sent to customers right after their order have been validated and confirmed
monostudio.mailing.mailgun.customer-order-confirmation-template=
# Template name for mails sent to customers right after their order have been rejected
monostudio.mailing.mailgun.customer-order-rejection-template=
# Template name for mails sent to customers right after their order have been completed/delivered
monostudio.mailing.mailgun.customer-order-completion-template=
# Template name for mails sent to owners/employees right after a new order has been confirmed
monostudio.mailing.mailgun.owner-order-confirmation-template=
# (Not used) Template name for mails sent to owners/employees right after a new order has been rejected
monostudio.mailing.mailgun.owner-order-rejection-template=
# (Not used) Template name for mails sent to owners/employees right after a new order has been completed/delivered
monostudio.mailing.mailgun.owner-order-completion-template=
