package org.monostudio.jpa.services.predicates;

import org.monostudio.jpa.entities.QProductVariant;
import org.monostudio.jpa.services.PredicateService;

/**
 * QueryDSL predicate builder for ProductVariant.
 * QProductVariant is auto-generated by QueryDSL APT (Annotation Processor)
 * during the maven compile phase and placed in target/generated-sources/java.
 */
public interface ProductVariantsPredicateService
    extends PredicateService {
    QProductVariant basePath = QProductVariant.productVariant;
}
